- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.11.0
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.11.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.12.0
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.12.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.13.0
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.13.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.14.0
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.14.0?classifier=sources
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.14.1
- pkg:maven/io.prometheus/simpleclient_tracer_otel_agent@0.14.1?classifier=sources
