- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.0
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.1
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.1?classifier=sources
