- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@0.0.1-releasetest1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.0
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.1
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.1?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-pushgateway@1.3.2?classifier=sources
