- pkg:maven/io.prometheus/simpleclient_httpserver@0.0.25
- pkg:maven/io.prometheus/simpleclient_httpserver@0.0.25?classifier=sources
- pkg:maven/io.prometheus/simpleclient_httpserver@0.0.26
- pkg:maven/io.prometheus/simpleclient_httpserver@0.0.26?classifier=sources
- pkg:maven/io.prometheus/simpleclient_httpserver@0.1.0
- pkg:maven/io.prometheus/simpleclient_httpserver@0.1.0?classifier=sources
