- pkg:maven/io.github.bes2008.solution.agileway.metrics/agileway-metrics-supports-prometheus@4.1.0
- pkg:maven/io.github.bes2008.solution.agileway.metrics/agileway-metrics-supports-prometheus@4.1.0?classifier=sources
- pkg:maven/io.github.bes2008.solution.agileway.metrics/agileway-metrics-supports-prometheus@4.1.1
- pkg:maven/io.github.bes2008.solution.agileway.metrics/agileway-metrics-supports-prometheus@4.1.1?classifier=sources
