- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.2.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.2.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.2.1
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.2.1?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.3.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.3.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.4.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.4.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.5.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.5.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.6.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@0.6.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.0.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.0.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.1.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.1.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.1.1
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.1.1?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.2.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.2.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.3.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.3.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.4.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.4.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.4.1
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.4.1?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.5.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.5.0?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.5.1
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.5.1?classifier=sources
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.6.0
- pkg:maven/fr.davit/akka-http-metrics-prometheus_2.12@1.6.0?classifier=sources
