- pkg:maven/org.jeecgframework.nacos/nacos-prometheus@2.2.3
- pkg:maven/org.jeecgframework.nacos/nacos-prometheus@2.2.3?classifier=sources
- pkg:maven/org.jeecgframework.nacos/nacos-prometheus@2.3.2
- pkg:maven/org.jeecgframework.nacos/nacos-prometheus@2.3.2?classifier=sources
