- pkg:maven/org.kie.soup/kie-soup-dataset-prometheus@7.50.0.Final
- pkg:maven/org.kie.soup/kie-soup-dataset-prometheus@7.50.0.Final?classifier=sources
- pkg:maven/org.kie.soup/kie-soup-dataset-prometheus@7.51.0.Final
- pkg:maven/org.kie.soup/kie-soup-dataset-prometheus@7.51.0.Final?classifier=sources
- pkg:maven/org.kie.soup/kie-soup-dataset-prometheus@7.51.0.t20210303
- pkg:maven/org.kie.soup/kie-soup-dataset-prometheus@7.51.0.t20210303?classifier=sources
