- pkg:maven/me.dinowernli/java-grpc-prometheus@0.3.0
- pkg:maven/me.dinowernli/java-grpc-prometheus@0.3.0?classifier=sources
- pkg:maven/me.dinowernli/java-grpc-prometheus@0.5.0
- pkg:maven/me.dinowernli/java-grpc-prometheus@0.5.0?classifier=sources
