- pkg:maven/org.opendaylight.serviceutils/metrics-impl-prometheus@0.10.0?classifier=sources
- pkg:maven/org.opendaylight.serviceutils/metrics-impl-prometheus@0.9.0?classifier=sources
- pkg:maven/org.opendaylight.serviceutils/metrics-impl-prometheus@0.9.1?classifier=sources
- pkg:maven/org.opendaylight.serviceutils/metrics-impl-prometheus@0.9.2?classifier=sources
