- pkg:maven/org.apache.nifi/nifi-prometheus-nar@1.10.0?classifier=sources
- pkg:maven/org.apache.nifi/nifi-prometheus-nar@1.11.0?classifier=sources
- pkg:maven/org.apache.nifi/nifi-prometheus-nar@1.11.1?classifier=sources
