- pkg:maven/io.vertx/vertx-config-kubernetes-configmap-scala_2.12@3.4.2
- pkg:maven/io.vertx/vertx-config-kubernetes-configmap-scala_2.12@3.5.0
- pkg:maven/io.vertx/vertx-config-kubernetes-configmap-scala_2.12@3.5.0.Beta1
