- pkg:maven/eu.hansolo/charts@1.0.1
- pkg:maven/eu.hansolo/charts@1.0.1?classifier=sources
- pkg:maven/eu.hansolo/charts@1.0.2
- pkg:maven/eu.hansolo/charts@1.0.2?classifier=sources
- pkg:maven/eu.hansolo/charts@1.0.3
- pkg:maven/eu.hansolo/charts@1.0.3?classifier=sources
- pkg:maven/eu.hansolo/charts@1.0.4
- pkg:maven/eu.hansolo/charts@1.0.4?classifier=sources
- pkg:maven/eu.hansolo/charts@1.0.5
- pkg:maven/eu.hansolo/charts@1.0.5?classifier=sources
