- pkg:maven/com.owellox.android.charts/charts@1.0.0-alpha01?classifier=sources
- pkg:maven/com.owellox.android.charts/charts@1.0.0-alpha02?classifier=sources
- pkg:maven/com.owellox.android.charts/charts@1.0.0-alpha03?classifier=sources
