- pkg:maven/io.github.quickmsg/smqtt-metric-prometheus@1.1.0
- pkg:maven/io.github.quickmsg/smqtt-metric-prometheus@1.1.0?classifier=sources
- pkg:maven/io.github.quickmsg/smqtt-metric-prometheus@1.1.1
- pkg:maven/io.github.quickmsg/smqtt-metric-prometheus@1.1.1?classifier=sources
