- pkg:maven/io.avaje/config@0.1
- pkg:maven/io.avaje/config@0.1?classifier=sources
- pkg:maven/io.avaje/config@0.3
- pkg:maven/io.avaje/config@0.3?classifier=sources
- pkg:maven/io.avaje/config@1.0
- pkg:maven/io.avaje/config@1.0?classifier=sources
