- pkg:maven/com.pulumi/kubernetes@3.18.3?classifier=sources
- pkg:maven/com.pulumi/kubernetes@3.19.1?classifier=sources
- pkg:maven/com.pulumi/kubernetes@3.20.2?classifier=sources
- pkg:maven/com.pulumi/kubernetes@3.21.0-alpha.1658753928%2B8c9c5d6a?classifier=sources
- pkg:maven/com.pulumi/kubernetes@3.21.0-alpha.1658777684%2B139c3997?classifier=sources
