- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.1
- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.1?classifier=sources
- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.2
- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.2?classifier=sources
- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.3
- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.3?classifier=sources
- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.4
- pkg:maven/org.lyranthe.prometheus/monix21_sjs0.6_2.12@0.8.4?classifier=sources
