- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.10.0
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.10.0?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.11.0
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.11.0?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.11.1
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.11.1?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.12.0
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.12.0?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.0
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.0?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.1
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.1?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.2
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.2?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.3
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.3?classifier=sources
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.4
- pkg:maven/io.frees/frees-rpc-prometheus-server_2.12@0.13.4?classifier=sources
